// Mocks generated by Mockito 5.4.6 from annotations
// in liblogin/test/src/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:convert' as _i9;
import 'dart:typed_data' as _i11;

import 'package:flutter/foundation.dart' as _i7;
import 'package:flutter/services.dart' as _i5;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i2;
import 'package:http/http.dart' as _i3;
import 'package:liblogin/src/auth_models.dart' as _i4;
import 'package:liblogin/src/auth_service.dart' as _i12;
import 'package:liblogin/src/fusionauth_client.dart' as _i13;
import 'package:liblogin_native/liblogin_native.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:sign_in_with_apple/sign_in_with_apple.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIOSOptions_0 extends _i1.SmartFake implements _i2.IOSOptions {
  _FakeIOSOptions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_1 extends _i1.SmartFake
    implements _i2.AndroidOptions {
  _FakeAndroidOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_2 extends _i1.SmartFake implements _i2.LinuxOptions {
  _FakeLinuxOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_3 extends _i1.SmartFake
    implements _i2.WindowsOptions {
  _FakeWindowsOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_4 extends _i1.SmartFake implements _i2.WebOptions {
  _FakeWebOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_5 extends _i1.SmartFake implements _i2.MacOsOptions {
  _FakeMacOsOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_6 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_7 extends _i1.SmartFake
    implements _i3.StreamedResponse {
  _FakeStreamedResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_8 extends _i1.SmartFake implements _i4.LoginResponse {
  _FakeLoginResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTokenResponse_9 extends _i1.SmartFake implements _i4.TokenResponse {
  _FakeTokenResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMethodCodec_10 extends _i1.SmartFake implements _i5.MethodCodec {
  _FakeMethodCodec_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBinaryMessenger_11 extends _i1.SmartFake
    implements _i5.BinaryMessenger {
  _FakeBinaryMessenger_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthorizationCredentialAppleID_12 extends _i1.SmartFake
    implements _i6.AuthorizationCredentialAppleID {
  _FakeAuthorizationCredentialAppleID_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i2.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_0(this, Invocation.getter(#iOptions)),
          )
          as _i2.IOSOptions);

  @override
  _i2.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_1(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i2.AndroidOptions);

  @override
  _i2.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_2(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i2.LinuxOptions);

  @override
  _i2.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_3(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i2.WindowsOptions);

  @override
  _i2.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_4(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i2.WebOptions);

  @override
  _i2.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_5(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i2.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i7.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i7.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> write({
    required String? key,
    required String? value,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> read({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<bool> containsKey({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> delete({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, String>> readAll({
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i8.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i8.Future<Map<String, String>>);

  @override
  _i8.Future<void> deleteAll({
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i8.Future<bool?>.value(),
          )
          as _i8.Future<bool?>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i3.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i8.Future<_i3.Response>.value(
              _FakeResponse_6(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i8.Future<_i3.Response>);

  @override
  _i8.Future<_i3.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i8.Future<_i3.Response>.value(
              _FakeResponse_6(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i8.Future<_i3.Response>);

  @override
  _i8.Future<_i3.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i9.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i8.Future<_i3.Response>.value(
              _FakeResponse_6(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i8.Future<_i3.Response>);

  @override
  _i8.Future<_i3.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i9.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i8.Future<_i3.Response>.value(
              _FakeResponse_6(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i8.Future<_i3.Response>);

  @override
  _i8.Future<_i3.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i9.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i8.Future<_i3.Response>.value(
              _FakeResponse_6(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i8.Future<_i3.Response>);

  @override
  _i8.Future<_i3.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i9.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i8.Future<_i3.Response>.value(
              _FakeResponse_6(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i8.Future<_i3.Response>);

  @override
  _i8.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<_i11.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i8.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
          )
          as _i8.Future<_i11.Uint8List>);

  @override
  _i8.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i8.Future<_i3.StreamedResponse>.value(
              _FakeStreamedResponse_7(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i8.Future<_i3.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [JwtDecoderWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockJwtDecoderWrapper extends _i1.Mock implements _i12.JwtDecoderWrapper {
  MockJwtDecoderWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isExpired(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#isExpired, [token]),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> decode(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#decode, [token]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [FusionAuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFusionAuthClient extends _i1.Mock implements _i13.FusionAuthClient {
  MockFusionAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get domain =>
      (super.noSuchMethod(
            Invocation.getter(#domain),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#domain),
            ),
          )
          as String);

  @override
  String get signupOrigin =>
      (super.noSuchMethod(
            Invocation.getter(#signupOrigin),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#signupOrigin),
            ),
          )
          as String);

  @override
  String get clientID =>
      (super.noSuchMethod(
            Invocation.getter(#clientID),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#clientID),
            ),
          )
          as String);

  @override
  String get tenantID =>
      (super.noSuchMethod(
            Invocation.getter(#tenantID),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#tenantID),
            ),
          )
          as String);

  @override
  String get redirectUri =>
      (super.noSuchMethod(
            Invocation.getter(#redirectUri),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#redirectUri),
            ),
          )
          as String);

  @override
  _i8.Future<_i4.LoginResponse> login({
    required String? username,
    required String? password,
    String? scope,
    Map<String, dynamic>? device = const {},
    dynamic lastLoginCredentials,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #username: username,
              #password: password,
              #scope: scope,
              #device: device,
              #lastLoginCredentials: lastLoginCredentials,
            }),
            returnValue: _i8.Future<_i4.LoginResponse>.value(
              _FakeLoginResponse_8(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                  #scope: scope,
                  #device: device,
                  #lastLoginCredentials: lastLoginCredentials,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.LoginResponse>);

  @override
  _i8.Future<_i4.TokenResponse> oauthRefreshTokenGrant(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#oauthRefreshTokenGrant, [refreshToken]),
            returnValue: _i8.Future<_i4.TokenResponse>.value(
              _FakeTokenResponse_9(
                this,
                Invocation.method(#oauthRefreshTokenGrant, [refreshToken]),
              ),
            ),
          )
          as _i8.Future<_i4.TokenResponse>);

  @override
  _i8.Future<_i4.TokenResponse> resourceOwnerPasswordCredentialsGrant(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resourceOwnerPasswordCredentialsGrant, [
              username,
              password,
            ]),
            returnValue: _i8.Future<_i4.TokenResponse>.value(
              _FakeTokenResponse_9(
                this,
                Invocation.method(#resourceOwnerPasswordCredentialsGrant, [
                  username,
                  password,
                ]),
              ),
            ),
          )
          as _i8.Future<_i4.TokenResponse>);

  @override
  _i8.Future<_i4.TokenResponse> refreshTokenGrant(
    dynamic lastLoginCredentials,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokenGrant, [lastLoginCredentials]),
            returnValue: _i8.Future<_i4.TokenResponse>.value(
              _FakeTokenResponse_9(
                this,
                Invocation.method(#refreshTokenGrant, [lastLoginCredentials]),
              ),
            ),
          )
          as _i8.Future<_i4.TokenResponse>);

  @override
  _i8.Future<_i4.TokenResponse> appleIdpLogin({
    required String? identityToken,
    required String? authorizationCode,
    required String? identityProviderId,
    required String? redirectUri,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#appleIdpLogin, [], {
              #identityToken: identityToken,
              #authorizationCode: authorizationCode,
              #identityProviderId: identityProviderId,
              #redirectUri: redirectUri,
            }),
            returnValue: _i8.Future<_i4.TokenResponse>.value(
              _FakeTokenResponse_9(
                this,
                Invocation.method(#appleIdpLogin, [], {
                  #identityToken: identityToken,
                  #authorizationCode: authorizationCode,
                  #identityProviderId: identityProviderId,
                  #redirectUri: redirectUri,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.TokenResponse>);

  @override
  _i8.Future<_i4.TokenResponse> googleIdpLogin({
    required String? idToken,
    required String? identityProviderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#googleIdpLogin, [], {
              #idToken: idToken,
              #identityProviderId: identityProviderId,
            }),
            returnValue: _i8.Future<_i4.TokenResponse>.value(
              _FakeTokenResponse_9(
                this,
                Invocation.method(#googleIdpLogin, [], {
                  #idToken: idToken,
                  #identityProviderId: identityProviderId,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.TokenResponse>);

  @override
  _i8.Future<_i4.TokenResponse> exchangeAuthorizationCode(
    String? code,
    String? codeVerifier,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeAuthorizationCode, [code, codeVerifier]),
            returnValue: _i8.Future<_i4.TokenResponse>.value(
              _FakeTokenResponse_9(
                this,
                Invocation.method(#exchangeAuthorizationCode, [
                  code,
                  codeVerifier,
                ]),
              ),
            ),
          )
          as _i8.Future<_i4.TokenResponse>);
}

/// A class which mocks [MethodChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMethodChannel extends _i1.Mock implements _i5.MethodChannel {
  MockMethodChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i5.MethodCodec get codec =>
      (super.noSuchMethod(
            Invocation.getter(#codec),
            returnValue: _FakeMethodCodec_10(this, Invocation.getter(#codec)),
          )
          as _i5.MethodCodec);

  @override
  _i5.BinaryMessenger get binaryMessenger =>
      (super.noSuchMethod(
            Invocation.getter(#binaryMessenger),
            returnValue: _FakeBinaryMessenger_11(
              this,
              Invocation.getter(#binaryMessenger),
            ),
          )
          as _i5.BinaryMessenger);

  @override
  _i8.Future<T?> invokeMethod<T>(String? method, [dynamic arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#invokeMethod, [method, arguments]),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  _i8.Future<List<T>?> invokeListMethod<T>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#invokeListMethod, [method, arguments]),
            returnValue: _i8.Future<List<T>?>.value(),
          )
          as _i8.Future<List<T>?>);

  @override
  _i8.Future<Map<K, V>?> invokeMapMethod<K, V>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#invokeMapMethod, [method, arguments]),
            returnValue: _i8.Future<Map<K, V>?>.value(),
          )
          as _i8.Future<Map<K, V>?>);

  @override
  void setMethodCallHandler(
    _i8.Future<dynamic> Function(_i5.MethodCall)? handler,
  ) => super.noSuchMethod(
    Invocation.method(#setMethodCallHandler, [handler]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LibloginNative].
///
/// See the documentation for Mockito's code generation for more information.
class MockLibloginNative extends _i1.Mock implements _i14.LibloginNative {
  MockLibloginNative() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String?> getPlatformVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatformVersion, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<String?> getPlatformInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatformInfo, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> setAuthRedirectHandler(dynamic Function(String)? handler) =>
      (super.noSuchMethod(
            Invocation.method(#setAuthRedirectHandler, [handler]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> dispatchAuthRedirect(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#dispatchAuthRedirect, [url]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> login({
    required Uri? authUri,
    required String? redirectUri,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #authUri: authUri,
              #redirectUri: redirectUri,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [AppleSignInWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppleSignInWrapper extends _i1.Mock
    implements _i12.AppleSignInWrapper {
  MockAppleSignInWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.AuthorizationCredentialAppleID> getCredential() =>
      (super.noSuchMethod(
            Invocation.method(#getCredential, []),
            returnValue: _i8.Future<_i6.AuthorizationCredentialAppleID>.value(
              _FakeAuthorizationCredentialAppleID_12(
                this,
                Invocation.method(#getCredential, []),
              ),
            ),
          )
          as _i8.Future<_i6.AuthorizationCredentialAppleID>);
}

/// A class which mocks [GoogleSignInWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInWrapper extends _i1.Mock
    implements _i12.GoogleSignInWrapper {
  MockGoogleSignInWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String?> getIdToken() =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);
}
