// Mocks generated by Mockito 5.4.6 from annotations
// in liblogin/test/src/auth_bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:liblogin/src/auth_service.dart' as _i4;
import 'package:liblogin/src/login_config.dart' as _i3;
import 'package:logger/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginConfig_1 extends _i1.SmartFake implements _i3.LoginConfig {
  _FakeLoginConfig_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Logger get log =>
      (super.noSuchMethod(
            Invocation.getter(#log),
            returnValue: _FakeLogger_0(this, Invocation.getter(#log)),
          )
          as _i2.Logger);

  @override
  _i5.Stream<bool> get authRedirectStream =>
      (super.noSuchMethod(
            Invocation.getter(#authRedirectStream),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Stream<String> get accessTokenStream =>
      (super.noSuchMethod(
            Invocation.getter(#accessTokenStream),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i3.LoginConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeLoginConfig_1(this, Invocation.getter(#config)),
          )
          as _i3.LoginConfig);

  @override
  set codeVerifier(String? value) => super.noSuchMethod(
    Invocation.setter(#codeVerifier, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> signUp(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [username, password]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> initiateGoogleLogin() =>
      (super.noSuchMethod(
            Invocation.method(#initiateGoogleLogin, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> initiateAppleLogin() =>
      (super.noSuchMethod(
            Invocation.method(#initiateAppleLogin, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> initiateGoogleNativeLogin() =>
      (super.noSuchMethod(
            Invocation.method(#initiateGoogleNativeLogin, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> recoverPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#recoverPassword, [email]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> checkLoginStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkLoginStatus, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
